# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Main Page
email: semihorhan@yandex.com
description: >- # this means to ignore newlines until "baseurl:"
  Semih Orhan blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://semihorhan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: semihorhan_
github_username:  semihorhan

# Build settings
# theme: minimal-mistakes-jekyll 
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin    : "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives


name                     : "Semih Orhan"
description              : "An amazing website."


words_per_minute         : 200
search : true
# search_provider: algolia

# Reading Files
include:
  - _pages



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
      layout: single
      share: true
      related: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/semihorhan_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/semihorhan"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/semihorhn"

